-- Schema for the Devin orchestrator. Idempotent: safe to run on every boot.

-- One row per issue we are remediating. This table is the single source of
-- truth for both the state machine and the dashboard/metrics.
CREATE TABLE IF NOT EXISTS tasks (
  id               SERIAL PRIMARY KEY,
  repo             TEXT        NOT NULL,           -- "ericyhliu/superset"
  issue_number     INTEGER     NOT NULL,
  issue_title      TEXT        NOT NULL,
  issue_url        TEXT        NOT NULL,

  devin_session_id TEXT,                           -- null until a session is created
  status           TEXT        NOT NULL DEFAULT 'queued',
  status_detail    TEXT,                           -- raw status string from Devin
  acus_consumed    NUMERIC     NOT NULL DEFAULT 0, -- Devin compute units used (1 ACU ~= 15 min)
  last_message     TEXT,                           -- latest activity line from the session
  pr_url           TEXT,                           -- null until the PR opens
  error            TEXT,                           -- failure reason, if any

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),  -- issue received
  dispatched_at    TIMESTAMPTZ,                    -- Devin session created
  pr_opened_at     TIMESTAMPTZ,                    -- PR webhook arrived
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One task (and therefore one Devin session) per issue. The webhook handler
  -- relies on this for idempotency via INSERT ... ON CONFLICT DO NOTHING.
  UNIQUE (repo, issue_number)
);

-- Migrate existing tables (CREATE above only applies to a fresh DB).
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS acus_consumed NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS last_message  TEXT;

-- Dumb idempotency log: dedupes redelivered GitHub webhooks across all event
-- types. The handler inserts the X-GitHub-Delivery id first; a conflict means
-- "already processed, ignore".
CREATE TABLE IF NOT EXISTS webhook_deliveries (
  delivery_id  TEXT PRIMARY KEY,
  event        TEXT,
  received_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per workflow RUN. A "code quality" workflow spawns a Devin discovery
-- session that scans the repo and FILES issues; those issues then flow through
-- the normal tasks pipeline for remediation.
CREATE TABLE IF NOT EXISTS workflows (
  id                   SERIAL PRIMARY KEY,
  type                 TEXT        NOT NULL DEFAULT 'code_quality',
  status               TEXT        NOT NULL DEFAULT 'discovering', -- discovering | completed | failed
  status_detail        TEXT,
  discovery_session_id TEXT,
  issues_found         INTEGER     NOT NULL DEFAULT 0,
  error                TEXT,
  trigger              TEXT        NOT NULL DEFAULT 'manual',       -- manual | scheduled
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at         TIMESTAMPTZ
);

-- Issues generated by a workflow's discovery session (links a run to the issues
-- it filed; join to tasks on (repo, issue_number) for remediation status).
CREATE TABLE IF NOT EXISTS workflow_issues (
  id           SERIAL PRIMARY KEY,
  workflow_id  INTEGER     NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  repo         TEXT        NOT NULL,
  issue_number INTEGER     NOT NULL,
  title        TEXT        NOT NULL,
  file         TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (workflow_id, issue_number)
);

-- Simple key/value settings (e.g. whether the periodic schedule is active).
CREATE TABLE IF NOT EXISTS app_settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
